"""DITM v4 backtest — applies the cross-sectional scorer to the PIT panel.

Input:  ditm_backtest_pit.csv  (generated by build_pit_panel.py)
        10,767 rows × (scan_date, ticker, strike, ...) with PIT fundamentals.

Method:
  Each scan_date is a scoring cohort.  All (ticker, strike) rows within that
  cohort are passed together to score_universe() so the cross-sectional ranking
  mirrors exactly what the live scorer does.  This is the only valid way to
  backtest a cross-sectional model: score in sample groups that replicate the
  information set available at each point in time.

Output:
  ditm_backtest_v4.csv  — PIT panel + v4 ditm_score + tier columns
  Console               — per-tier IC, ROC, win-rate monotonicity table

Run from repo root:
    backend\\venv\\Scripts\\python.exe scripts\\backtest_ditm_v4.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from services.scoring.ditm_v4 import (   # noqa: E402
    Candidate,
    FACTOR_DEFINITIONS,
    score_universe,
    tier_for_score,
)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

IN_PATH  = ROOT / "ditm_backtest_pit.csv"
OUT_PATH = ROOT / "ditm_backtest_v4.csv"

# The 13 factor column names as they appear in the PIT CSV.
FACTOR_COLS = [name for name, *_ in FACTOR_DEFINITIONS]  # canonical order


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------

def score_cohort(group: pd.DataFrame) -> pd.DataFrame:
    """Score one scan_date cohort cross-sectionally; adds v4_score + v4_tier."""
    candidates = [
        Candidate(
            id=str(idx),
            factors={col: (None if pd.isna(row[col]) else float(row[col]))
                     for col in FACTOR_COLS},
        )
        for idx, row in group.iterrows()
    ]
    scored = score_universe(candidates)
    id_to_score = {s.id: s.score for s in scored}

    group = group.copy()
    group["v4_score"] = group.index.map(lambda i: id_to_score.get(str(i), 0.0))
    group["v4_tier"]  = group["v4_score"].apply(
        lambda s: tier_for_score(s) if s is not None and not (isinstance(s, float) and np.isnan(s)) else "E"
    )
    return group


def apply_v4_scores(df: pd.DataFrame) -> pd.DataFrame:
    """Apply cross-sectional v4 scoring to every scan_date cohort."""
    n_cohorts = df["scan_date"].nunique()
    print(f"Scoring {n_cohorts} scan-date cohorts ({len(df)} rows)...")
    parts = []
    for i, (date, grp) in enumerate(df.groupby("scan_date"), 1):
        parts.append(score_cohort(grp))
        if i % 20 == 0 or i == n_cohorts:
            print(f"  {i}/{n_cohorts} cohorts scored")
    return pd.concat(parts).sort_values(["scan_date", "ticker", "strike"])


# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

def summarise(df: pd.DataFrame) -> None:
    df = df.dropna(subset=["v4_score", "realised_roc_annualised"]).copy()
    n = len(df)

    print(f"\n{'=' * 72}")
    print(f"DITM v4 BACKTEST  —  {n:,} trades  ·  "
          f"{df['ticker'].nunique()} tickers  ·  "
          f"{df['scan_date'].min()} → {df['scan_date'].max()}")
    print(f"{'=' * 72}\n")

    # --- Spearman IC -------------------------------------------------------
    rho, p = spearmanr(df["v4_score"], df["realised_roc_annualised"])
    rho_pnl, p_pnl = spearmanr(df["v4_score"], df["pnl_per_contract"])
    print(f"Spearman IC (v4_score vs realised_roc_annualised): "
          f"rho = {rho:+.4f}   p = {p:.4g}   n = {n}")
    print(f"Spearman IC (v4_score vs pnl_per_contract):        "
          f"rho = {rho_pnl:+.4f}   p = {p_pnl:.4g}\n")

    # Baseline: old v3 final_score IC for comparison
    if "final_score" in df.columns:
        rho3, p3 = spearmanr(df["final_score"].dropna(),
                             df.loc[df["final_score"].notna(), "realised_roc_annualised"])
        print(f"Baseline v3 IC (final_score vs realised_roc): "
              f"rho = {rho3:+.4f}   p = {p3:.4g}   (reference only)\n")

    # --- Per-tier table ----------------------------------------------------
    TIER_ORDER = ["A", "B", "C", "D", "E"]
    rows = []
    for tier in TIER_ORDER:
        g = df[df["v4_tier"] == tier]
        if g.empty:
            continue
        rows.append({
            "Tier": tier,
            "n": len(g),
            "%": f"{100*len(g)/n:.1f}%",
            "Score min": f"{g['v4_score'].min():.0f}",
            "Score max": f"{g['v4_score'].max():.0f}",
            "Mean ROC": f"{g['realised_roc_annualised'].mean():.1f}%",
            "Median ROC": f"{g['realised_roc_annualised'].median():.1f}%",
            "Win %": f"{100*(g['pnl_per_contract']>0).mean():.1f}%",
            "ITM %": f"{100*g['in_the_money_at_exp'].mean():.1f}%",
            "Mean PnL $": f"{g['pnl_per_contract'].mean():.0f}",
        })
    tier_df = pd.DataFrame(rows).set_index("Tier")
    print("Per-tier breakdown:")
    print(tier_df.to_string())

    # Monotonicity check: mean ROC A > B > C > D > E?
    means = [float(df[df["v4_tier"]==t]["realised_roc_annualised"].mean())
             for t in TIER_ORDER if not df[df["v4_tier"]==t].empty]
    monotone = all(means[i] >= means[i+1] for i in range(len(means)-1))
    print(f"\nMonotonicity (A→E mean ROC): {'✓ YES' if monotone else '✗ NOT FULLY MONOTONE'}")
    print("  " + "  >  ".join(f"{m:.1f}%" for m in means))

    # --- Per-decile IC lift ------------------------------------------------
    df["v4_decile"] = pd.qcut(df["v4_score"], 10, labels=[f"D{i+1}" for i in range(10)],
                               duplicates="drop")
    dg = df.groupby("v4_decile", observed=True).agg(
        n   = ("v4_score", "size"),
        s_lo= ("v4_score", "min"),
        s_hi= ("v4_score", "max"),
        mean_roc  = ("realised_roc_annualised", "mean"),
        median_roc= ("realised_roc_annualised", "median"),
        win_pct   = ("pnl_per_contract", lambda x: 100*(x>0).mean()),
        mean_lev  = ("leverage", "mean"),
    ).round(2)
    print(f"\nDecile breakdown (D1=lowest score → D10=highest):")
    print(dg.to_string())

    # --- Per-factor IC (sanity check) -------------------------------------
    print(f"\nPer-factor Spearman IC vs realised_roc_annualised:")
    print(f"  {'factor':>16}  {'rho':>8}  {'p':>9}")
    for col in FACTOR_COLS:
        if col not in df.columns:
            continue
        s = df.dropna(subset=[col, "realised_roc_annualised"])
        if len(s) < 50:
            continue
        rho_f, p_f = spearmanr(s[col], s["realised_roc_annualised"])
        flag = " *" if p_f < 0.05 else ""
        print(f"  {col:>16}  {rho_f:+.4f}   {p_f:.4g}{flag}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    if not IN_PATH.exists():
        print(f"ERROR: {IN_PATH} not found. Run build_pit_panel.py first.")
        sys.exit(1)

    df = pd.read_csv(IN_PATH)
    print(f"Loaded {len(df):,} rows from {IN_PATH.name}")

    # Validate required columns
    missing = [c for c in FACTOR_COLS if c not in df.columns]
    if missing:
        print(f"WARNING: missing factor columns (will be imputed as None): {missing}")

    df = apply_v4_scores(df)
    df.to_csv(OUT_PATH, index=False)
    print(f"\nSaved scored panel → {OUT_PATH.name}  ({len(df):,} rows)")

    summarise(df)


if __name__ == "__main__":
    main()
